services:
  postgres:
    image: postgres:15
    platform: linux/amd64
    container_name: ulearner-postgres
    environment:
      POSTGRES_DB: ulearnerdb
      POSTGRES_USER: ulearner
      POSTGRES_PASSWORD: 29082006artychanal
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ulearner -d ulearnerdb" ]
      interval: 5s
      timeout: 5s
      retries: 5

  postgres-test:
    image: postgres:15
    platform: linux/amd64
    container_name: ulearner-postgres-test
    environment:
      POSTGRES_DB: ulearnerdb_test
      POSTGRES_USER: ulearner
      POSTGRES_PASSWORD: 29082006artychanal
    ports:
      - "5435:5432"
    tmpfs:
      - /var/lib/postgresql/data  # Временное хранилище для тестов
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ulearner -d ulearnerdb_test" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: